### PR TITLE
nav bar initial styling

### PR DESCRIPTION
**Pull request by hxrts**
These haven't been tested on mobile but everything looks ok locally on my laptop. May want to push to a staging site if you have one to take a look on your phone. Code still needs to be cleaned up a bunch.

### CODE REVIEW

**Comment by hxrts** [comment]
Pull request is still outstanding and seems the styling hasn't been fixed otherwise. Is there anything you'd like done before merging or are we deciding to drop this in lieu of a more complete refactor?

**Comment by mathisonian** [comment]
Thanks @hxrts, this looks good - big improvement from the current mobile experience. Apologies it's been sitting so long. 

I'm going to merge as is, but would be open to some updates of the bottom nav still. @michaelconnor @despens any thoughts here?

**Comment by jsnhff** [comment]
Glad this is finally merged!

**Comment by hxrts** [comment]
Thanks all. My first pull Rhizome pull request! Far from a perfect fix but it's a step in the right direction. Welcome any feedback moving forward.

**Comment by protonpopsicle** [comment]
:turtle: sry for the lateness!
+1 @mathisonian

**Pull request merged**
